YOUTUBE_CLIENT_ID = ""
YOUTUBE_CLIENT_SECRET = ""
YOUTUBE_API_KEY = ""

YOUTUBE_CHANNEL_IDS = []

MODE = 'audio'  # video or audio

TELEGRAM_API_ID = 0
TELEGRAM_API_HASH = ''
TELEGRAM_BOT_TOKEN = ''
TELEGRAM_CHAT_ID = 0
